{"timestamp":"2025-08-17T19:17:12.887648","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-17T19:17:12.891874","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/retrain_the_model.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-17T19:17:14.901330","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:17:17.076978","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:17:18.941570","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:17:19.039910","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:17:19.141885","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:17:19.219406","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:17:19.873786","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:17:20.062409","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:17:20.326646","level":"warning","event":"Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5851ce60>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:17:24.570861","level":"warning","event":"Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff586b5be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:17:33.249560","level":"warning","event":"Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff586756a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:17:50.090986","level":"warning","event":"Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58674ec0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:18:22.599340","level":"warning","event":"Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58674530>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:19:26.744256","level":"warning","event":"Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58674260>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:21:26.765213","level":"warning","event":"Retrying (Retry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58674650>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:21:26.794083Z","level":"info","event":"No champion model found. Training initial model...","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-17T19:21:26.889519","level":"warning","event":"Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58676b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:21:31.208183","level":"warning","event":"Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58676420>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:21:39.621944","level":"warning","event":"Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58676f60>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:21:56.620655","level":"warning","event":"Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58675b80>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:22:29.551880","level":"warning","event":"Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff58676360>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:23:33.782934","level":"warning","event":"Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff59dd06e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
