{"timestamp":"2025-08-17T19:31:39.822006","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-17T19:31:39.822942","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/retrain_the_model.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-17T19:31:40.640867","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:31:40.988464","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:31:41.809058","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:31:41.904872","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:31:41.966191","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:31:42.049691","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:31:42.336822","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:31:42.530580","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:31:42.691407","level":"warning","event":"Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5449e990>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:31:47.600791","level":"warning","event":"Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff4cd23c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:31:56.059574","level":"warning","event":"Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff4cd71940>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:32:12.618867","level":"warning","event":"Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff4ceb93d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:32:45.315035","level":"warning","event":"Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff4ceba810>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
