{"timestamp":"2025-08-17T19:17:48.592102","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-17T19:17:48.593468","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/retrain_the_model.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-17T19:17:49.325693","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:17:49.502051","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:17:50.403550","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:17:50.483677","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:17:50.533803","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:17:50.658601","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:17:50.909467","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T19:17:50.983544","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T19:17:51.137419","level":"warning","event":"Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff59db7a40>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:17:55.261482","level":"warning","event":"Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a78d790>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:18:03.540943","level":"warning","event":"Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff59d85430>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:18:19.832183","level":"warning","event":"Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a75cb30>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:18:52.386242","level":"warning","event":"Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff59e12600>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:19:56.579033","level":"warning","event":"Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff59e12390>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:21:56.681036","level":"warning","event":"Retrying (Retry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff59e10590>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:21:56.749457Z","level":"info","event":"No champion model found. Training initial model...","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-17T19:21:56.834787","level":"warning","event":"Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a727080>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:22:01.772166","level":"warning","event":"Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a726a20>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:22:10.280004","level":"warning","event":"Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a727440>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:22:26.827100","level":"warning","event":"Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a726d50>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-17T19:22:59.283419","level":"warning","event":"Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff5a726f00>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Airbnb+Buenos+Aires","logger":"urllib3.connectionpool"}
